### ISSUE TITLE
Algebrite pauses debugger

### ISSUE THREAD

**Issue by Mathmagician8191** [davidedc/Algebrite#96] opened 2019-09-12 23:35 UTC
Algebrite occasionally goes into a state where Chrome says: "Paused in debugger"
The following code seems to be responsible, starting at line 24161 in algebrite.bundle-for-browser.js:
```
check_stack = function() {
    if (tos !== 0) {
      debugger;
      stop("stack error");
    }
    if (frame !== TOS) {
      debugger; //This line triggers
      stop("frame error");
    }
```
check_stack is called in line 24724
Browser: Chrome 76.0.3809.132 (64-bit)
OS: Windows 10

**Comment by davidedc** [comment] 2019-09-13 21:01
Hi - yes this is intended behaviour in case there is a stack or frame error.

Closing for the time being, while the command or program causing this is added to the issue.

Feel free to re-open if you get around to that.

**Closed by davidedc** 2019-09-13 21:01 UTC
